### PR TITLE
Add more targets

### PR DESCRIPTION
**Pull request by kassane**
closes: #97 
cc: @marler8997

### CODE REVIEW

**Comment by kassane** [comment]
LGTM?

**Comment by kassane** [comment]
updated and rebased

**Comment by marler8997** [comment]
just because it make the CI take longer, I'd like to limit zigup to targets that people are actually using.  If anyone wants to claim they are using any of these new targets I'm happy to add them at that point.

**Comment by kassane** [comment]
> If anyone wants to claim they are using any of these new targets I'm happy to add them at that point.

https://github.com/kassane/docker-zig

**Comment by marler8997** [comment]
I took your changes and reworked them to apply to master and added you as co-author in this commit: https://github.com/marler8997/zigup/commit/50482ca26007e3a2814e20696caba22c9faebbc0

Changes are now merged and I'm about to release them.

**Pull request closed without merging**
