### PR TITLE
Fixed compilation for zig 0.13

### PR DESCRIPTION
**Pull request by pierrelgol**
Simple rename of all the std.ChildProcess --> std.process.Child

### CODE REVIEW

**Comment by marler8997** [comment]
Could you squash into 1 commit and also fix artifacts.yml to point to 0.13.0?

**Comment by pierrelgol** [comment]
yep no problem sorry didn't check that

**Comment by pierrelgol** [comment]
I get compilation issues with the zig build ci for macos targets and I don't really know ho to fix it sorry

**Comment by marler8997** [comment]
Thanks!

**Comment by pierrelgol** [comment]
Thank you for the awesome project it has been my goto for managing zig versions

**Comment by chenrui333** [comment]
@marler8997 any chance of cutting a new release for this PR change? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/202961

**Comment by marler8997** [comment]
Sure, here's the latest release: https://github.com/marler8997/zigup/releases/tag/v2025_01_02

**Pull request merged**
