### PR TITLE
add support for 3rd party index

### PR DESCRIPTION
**Pull request by mangas**
Implements https://github.com/marler8997/zigup/issues/134

- Add flag to override the index to fetch the tarball link from.

### CODE REVIEW

**Comment by mangas** [comment]
The cosmetic changes were done by zig fmt on save, if needed I can remove them.

**Comment by marler8997** [comment]
thanks for the contribution.  I went ahead and ran `zig fmt` and pushed to master.  Do you mind rebasing and/or reworking the change off of master so I don't have to wade through the formatting changes?

**Comment by mangas** [comment]
There are still some small cosmetic changes but seems a lot easier to parse now. Let me know if this is close enough otherwise I can try to make the changes and turn off the formatting

**Comment by marler8997** [comment]
such a simple change/enhancement, I'm just going to merge this as is.  Would be nice to add a test but can be done later.

**Comment by mangas** [comment]
I'll have a look at the tests and see if I can add one that uses this flag

**Pull request merged**
